### ISSUE TITLE
Non-pinned buffers

### ISSUE THREAD

**Issue by buybackoff** [Horusiath/vergil#1]
(I realize this maybe experimental or even throw-away project, but still...)

Just out of curiosity followed to this project from https://github.com/Spreads/Spreads.LMDB/network/dependents and found (quite common) incorrect usage w.r.t. not pinned buffers.

https://github.com/Horusiath/vergil/blob/c37f3f34636dd0cbf2e5e020a0109722e2794cf5/src/Vergil.Lmdb/LmdbArchive.cs#L113-L126

The line `new DirectBuffer(buffer);` does not pin it for you. Also, it looks like you do not return the buffer back to the pool, so this is effectively `new[]`. For reading primitive values there is generics support that does not require temp buffers or pinning because primitives work on the stack.

Technically `var key = OffsetKey;` also needs to be pinned, but as `static readonly span` it likely never moves.

In another project `stackalloc` is OK and exactly what the primitive generic support does, but this line has the same problem if it returns just unpinned `byte[]`: https://github.com/Horusiath/Eventuate.NET/blob/master/src/Eventuate.Lmdb/LmdbEventLog.cs#L190

It's just a time bomb when GC will move unpinned buffer, especially given that you allocate and drop buffers so GC0 probably does happen a lot.

Just using `fixed` keyword for `byte[]` buffers will fix that without much performance impact.

The DirectBuffer constructor works via implicit cast from `byte[]` to `Span` and then this code, which assumes the `Span` is already pinned:

```
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public DirectBuffer(Span<byte> span)
        {
            _length = (IntPtr)span.Length;
            _pointer = (byte*)Unsafe.AsPointer(ref span.GetPinnableReference());
        }
```

**Comment by Horusiath** [comment]
Thanks @buybackoff for clarification. So far I'm still exploring the Spreads.LMDB API, searching for the best way to provide buffers that can be pooled and do not require from me allocating arrays `byte[]` of exact size.

**Comment by buybackoff** [comment]
API takes `DirectBuffer`, which has a size in its ctor (you could slice a `Span` or `DirectBuffer` after creation). 

Also there is a memory pool that works with already pinned arrays (you already have it as a dependency `Spreads.Core` where `DirectBuffer` lives). It works with slabs of 128kb so that they are always in LOH and being pinned for a long time does not create fragmentation. Here its ctor: https://github.com/Spreads/Spreads/blob/4b2a7f7676974b3feb7de204f58a64f437c797aa/src/Spreads.Core/Buffers/BufferPool.cs#L34-L56

It implements `System.Memory.MemoryPool<T>` and pools not only underlying buffers but also `IMemoryOwner<T>` instances. If you ever need completely zero-alloc this may be useful.

But just pinning on demand via `fixed` should be fine. Even a `Span` has `GetPinnableReference` that works in the `fixed` statement.

If you could avoid the heap completely then `stackalloc` in the right thing.
